environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - git checkout package-lock.json

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run lint
  - npm run demo
  - npm run online

build: off
